title: My AWS Portfolio
description: >
  A portfolio showcasing AWS services.
theme: slate

# Optional configurations
# baseurl: "/AWS-Portfolio" # Uncomment and set if your site is in a subdirectory
url: "https://yourusername.github.io"

# Enable or disable plugins
plugins:
  - jekyll-feed

